language: python
python: "2.7"

sudo: required

services:
  - docker

branches:
  only:
    - master
    - dev

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible
  - if [ -f 'requirements.yml' ]; then yum -y install git && ansible-galaxy install -r requirements.yml; fi

  # version checks
  - docker --version
  - docker-compose --version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - ansible-playbook test.yml --syntax-check
  - ansible-playbook test.yml -vvv -c local -b

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
